apiVersion: ignite.weave.works/v1alpha4
kind: VM
metadata:
  name: my-vm
  uid: 599615df99804ae8
spec:
  image:
    oci: sayysf/my-vm:001
  cpus: 2
  diskSize: 3GB
  memory: 800MB
  ssh: true
status:
  running: true

